### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by MiloCasagrande** [marko-js/webpack#27]
### Details

After updating to the latest version of `@marko/webpack`, when I load the app in the browser I get the following error message:

`Cannot assign to read only property 'exports' of object '#<Object>'`

This prevents the rest of the app to work correctly.

When compiling the project, I also get the following warning:

`"export 'default' (imported as 'component') was not found in './index.marko'`

repeated multiple times (for each component).

I'm not sure if this is the expected behavior for `@marko/webpack` `4.1.1`, if it's a breaking change compared to the way components are written.

### Your Environment

- Chrome (latest)
- Firefox (latest) 
- nodejs 12
- MacOS, Linux

### Steps to Reproduce

I tried also with the `marko-webpack` repository from the markojs examples updating all dependencies to the latest available versions, and I get the same error.

https://github.com/MiloCasagrande/marko-webpack/tree/marko-webpack-4.1.1

**Comment by DylanPiercey** [comment]
Should be fixed in `4.1.2`. Thanks for filing the issue 😄
