### ISSUE TITLE
Cache Marko Files

### ISSUE THREAD

**Issue by Khauri** [marko-js/webpack#39]
### Description

As per a comment by @DylanPiercey on [gitter](https://gitter.im/marko-js/marko?at=5f0f21d5e3505d7736ffdc65)

> Marko files are marked as non cachable in webpack because we don’t currently have a good way to tell webpack all of the folders and files that, although unreferenced in the compiled code, can cause the compilation to change.

So basically, I think it would be very valuable if marko files were cached during builds.

### Why

I have been attempting to migrate my company's large-ish project from lasso to webpack. The last hurdle appears to be supporting a fast development environment. Though I'm not entirely sure if caching is the sole reason for this, every rebuild while using webpack's watch mode causes all the marko files, and only the marko files, across the app to be rebuilt even if they haven't changed. We have quite a few marko components so this ends up taking a while.

### Possible Implementation & Open Questions

I had some small results by using [cache-loader](https://webpack.js.org/loaders/cache-loader/) to cache the results of the marko-loader, however when running webpack in build mode, modifications wouldn't show up. And although this was faster, I wouldn't necessarily call it fast. It may be worth looking into how the cache-loader operates if there isn't already an idea on where to begin with this.

### Is this something you're interested in working on?

In the interest of getting my team's project on to webpack faster I'd be willing to provide as much support for this issue as possible, though I'm not all that knowledgeable about Marko internals or webpack loaders.

I've also been documenting the migration process and would be willing to contribute to a lasso to webpack migration guide.

**Comment by timmclaughlin** [comment]
We are having the same problem!  Can't really use webpack because of it.

**Comment by DylanPiercey** [comment]
Marko files now support caching, even with the filesystem based cache in webpack 5.
