### ISSUE TITLE
Marko stopped working after upgrade to 5.31.16

### ISSUE THREAD

**Issue by xtremespb** [marko-js/webpack#84]
### Details

heretic@1.1.107 /Users/xtreme/Documents/GitHub/heretic
├─┬ @marko/webpack@9.3.4
│ └── marko@5.31.16 deduped
└─┬ marko@5.31.16
  └─┬ @marko/translator-default@5.31.6
    └── marko@5.31.16 deduped

### Expected Behavior

Everything was fine on 5.31.14. I expect the same behaviour on 5.31.16 ;-)

### Actual Behavior

There is no re-hydration of server code, and the page is empty. The JS events are not triggered (e.g. onMount)

### Possible Fix

Currently the only way for me is to downgrade to 5.31.14.

<details><summary>Additional Info</summary>

### Your Environment

Mac OS Sonoma, MacBook Pro, 32 GB RAM
Vivaldi 6.2.3105.58

### Steps to Reproduce

1. Clone https://github.com/hereticjsorg/heretic.git
2. npm i 
3. npm run configure
4. npm run build -- --dev  
5. npm run server
6. Go to http://127.0.0.1:3001

</details>

**Comment by DylanPiercey** [comment]
@xtremespb thanks for the report and info.

This was in fact a regression over here. `@marko/webpack@9.3.5` has the fix

**Comment by xtremespb** [comment]
Thank you, it works! 👍
